name: e2e tests

on: [push]

jobs:
  test:
    defaults:
      run:
        working-directory: ./apps/yet-another-testing-dApp
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.36.2-focal
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install

      - name: Run e2e tests
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: xvfb-run --auto-servernum yarn test:ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
